# .rubocop.yml

# Enable all cops

# Target Ruby version

AllCops:
  DisabledByDefault: false
  TargetRubyVersion: 3.2.2

# Add other configuration options as needed
# For example, you can exclude certain files or directories
# from being analyzed by Rubocop using the `Exclude` option.

# AllCops:
#   Exclude:
#     - path/to/excluded/file.rb
#     - path/to/excluded_directory/**
